// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.mpi-internal.com/juan-ibars/learning-go/internal/domain"

	uuid "github.com/google/uuid"
)

// AdRepository is an autogenerated mock type for the AdRepository type
type AdRepository struct {
	mock.Mock
}

// FindAllAds provides a mock function with given fields:
func (_m *AdRepository) FindAllAds() []domain.Ad {
	ret := _m.Called()

	var r0 []domain.Ad
	if rf, ok := ret.Get(0).(func() []domain.Ad); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Ad)
		}
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *AdRepository) FindById(id uuid.UUID) *domain.Ad {
	ret := _m.Called(id)

	var r0 *domain.Ad
	if rf, ok := ret.Get(0).(func(uuid.UUID) *domain.Ad); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Ad)
		}
	}

	return r0
}

// Save provides a mock function with given fields: ad
func (_m *AdRepository) Save(ad domain.Ad) {
	_m.Called(ad)
}

type mockConstructorTestingTNewAdRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdRepository creates a new instance of AdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdRepository(t mockConstructorTestingTNewAdRepository) *AdRepository {
	mock := &AdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
