// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// IdGenerator is an autogenerated mock type for the IdGenerator type
type IdGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *IdGenerator) Generate() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

type mockConstructorTestingTNewIdGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewIdGenerator creates a new instance of IdGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIdGenerator(t mockConstructorTestingTNewIdGenerator) *IdGenerator {
	mock := &IdGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
