// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TimeGenerator is an autogenerated mock type for the TimeGenerator type
type TimeGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *TimeGenerator) Generate() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

type mockConstructorTestingTNewTimeGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewTimeGenerator creates a new instance of TimeGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTimeGenerator(t mockConstructorTestingTNewTimeGenerator) *TimeGenerator {
	mock := &TimeGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
