version: '3.4'

services:
  postgresql:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: challenges

